In [4]:
import numpy
data = [1.,2, "3"]
numpy.array(data)

array(['1.0', '2', '3'], dtype='<U32')

In [12]:
import numpy

my_array = numpy.array([1, 2, 3, 4, 5])
print(my_array)

my_array_2 = numpy.arange(1, 6)  # последовательность от 1 до 5
print(my_array_2)

my_array_3 = numpy.linspace(1, 5, 5)  # равномерная последовательность в интервале 1 до 5 на 5 элементов
print(my_array_3)

[1 2 3 4 5]
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [16]:
import numpy

my_array = numpy.array([[1, 2], [3, 4]])
print(my_array)

my_array_2 = numpy.zeros((3, 4))  # матрица из нулей 3х4
print(my_array_2)

my_array_3 = numpy.ones((2, 3))  # матрица из единиц 2х3
print(my_array_3)

[[1 2]
 [3 4]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
import numpy

iterator = numpy.arange(1., 2., 0.1)

print(iterator)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [20]:
import numpy

# Создание двух одномерных векторов
vector1,vector2 = numpy.array([1, 2, 3]),numpy.array([4, 5, 6])

vertical_concatenation = numpy.vstack((vector1, vector2))
horizontal_concatenation = numpy.hstack((vector1, vector2))

print("Вертикальная конкатенация:\n", vertical_concatenation)
print("Горизонтальная конкатенация:", horizontal_concatenation)


Вертикальная конкатенация:
 [[1 2 3]
 [4 5 6]]
Горизонтальная конкатенация: [1 2 3 4 5 6]


In [22]:
import numpy

# Создание двух двумерных векторов
vector1,vector2 = numpy.array([[1, 2], [3, 4]]),numpy.array([[5, 6], [7, 8]])

vertical_concatenation = numpy.vstack((vector1, vector2))
horizontal_concatenation = numpy.hstack((vector1, vector2))

print("Вертикальная конкатенация:\n", vertical_concatenation)
print("Горизонтальная конкатенация:\n", horizontal_concatenation)

Вертикальная конкатенация:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтальная конкатенация:
 [[1 2 5 6]
 [3 4 7 8]]


In [29]:
import numpy 

array = numpy.array([1, 2, 3, 4, 5])
print("Тип данных исходного массива:", array.dtype)

# меняем на int
int_array = original_array.astype(numpy.int)
print(int_array,"Тип данных массива int:", int_array.dtype)

# меняем на float
float_array = array.astype(numpy.float)
print(float_array, "Тип данных массива float:", float_array.dtype)

# меняем на string
string_array = array.astype(numpy.str)
print(string_array,"Тип данных массива string:", string_array.dtype)


Тип данных исходного массива: int64
[1 2 3 4 5] Тип данных массива int: int64
[1. 2. 3. 4. 5.] Тип данных массива float: float64
['1' '2' '3' '4' '5'] Тип данных массива string: <U21
edn


/var/folders/r2/lzhd4pmn3dzdzqs17wgy75_r0000gn/T/ipykernel_42073/4059177623.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int_array = original_array.astype(numpy.int)
/var/folders/r2/lzhd4pmn3dzdzqs17wgy75_r0000gn/T/ipykernel_42073/4059177623.py:11: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details a

In [28]:
import numpy

vector = numpy.array([[1, 2, 3]])  
print(vector, "Форма исходного вектора:", vector.shape)
result = numpy.squeeze(vector)
print(result, "Форма вектора после удаления оси:", result.shape)

[[1 2 3]] Форма исходного вектора: (1, 3)
[1 2 3] Форма вектора после удаления оси: (3,)
